baseURL = 'https://merlinds.github.io'
languageCode = 'en-us'
title = 'MerlinDS Site'
theme = 'hello-friend'

[params]
	contentTypeName = "posts"
	defaultTheme = "dark"
	showMenuItems = 2
	showReadingTime = true
	disqusShortname = 'https-merlinds-github-io'
	
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4

[languages]
	[languages.en]
		title = "MerlinDS"
		subtitle = "Hi friend"
	
	[languages.en.params.logo]
		logoText = "merlinds"
		logoHomeLink = "/about"
		
	[languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts"
	